### ISSUE TITLE
During make build, the /opt/conda/bin missing.

### ISSUE THREAD

**Issue by muh-hassani** [jupyterhub/jupyterhub-deploy-docker#100]
When I followed the instructions to build the docker-compose file via  `make build,` I faced an error, which suggests `/opt/conda/bin/conda` is missing. I read in a [closed issue](https://github.com/jupyterhub/jupyterhub-deploy-docker/issues/91) about it and also about the suggested solution. Unfortunately, updating conda does not help to solve this issue.
As a workaround, I built miniconda from the source in the right path before using conda to install the requirements. But I believe this issue should be solved, or at least the instruction or the Dockerfile.jupyterhub should be modified accordingly.

My host os is Ubuntu 18.04 and I tried to build the docker image from the latest version of the jupyterhub/jupyterhub-onbuild image.

**Comment by Quitte007** [comment]
"or at least the instruction or the Dockerfile.jupyterhub should be modified accordingly. "

Not complaining at all because this solved my Problem, but this isnt that hard right? Thx

**Comment by muh-hassani** [comment]
> 
> 
> "or at least the instruction or the Dockerfile.jupyterhub should be modified accordingly. "
> 
> Not complaining at all because this solved my Problem, but this isnt that hard right? Thx

Yes, true. It was not hard at all, but it is good to have it documented somewhere.
I guess, I should close this issue any way.
