### ISSUE TITLE
How to get a Docker image created by repo2docker to work?

### ISSUE THREAD

**Issue by P-Mikkola** [jupyterhub/jupyterhub-deploy-docker#101]
Hi All,

First of all, I would like to thank the contributors of the project. I have found this repository very useful.
**I think it would be great if there were instructions for setting up a JupyterHub to spawn Notebook servers from a Docker image created by repo2docker.** This would be make many lives easier, since then configuring a customized enviroment would be very easy (gitrepo ---repo2docker---> dockerimage ---jupyterhub-deploy-docker---> customized jupyterhub enviroment).

Note that, for instance, the following instruction on README does not give much (concrete) help on what one has to do to get an arbitrary docker image working:
"_You can configure JupyterHub to spawn Notebook servers from any Docker image, as long as the image's ENTRYPOINT and/or CMD starts a single-user instance of Jupyter Notebook server that is compatible with JupyterHub._".

All the best!

**Comment by manics** [comment]
Hi! Support questions like this are best handled on https://discourse.jupyter.org/
