### ISSUE TITLE
Extension file

### ISSUE THREAD

**Issue by brunocampos01** [jupyterhub/jupyterhub-deploy-docker#102]
https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/d2bed7a1ce5e2b140e0eea6c3781bbd7154268e7/examples/letsencrypt/docker-compose.yml#L22

The correct thing would be: `/etc/letsencrypt/privkey.key` ?

**Comment by 7yl4r** [comment]
The file extension doesn't matter to jupyterHub. I don't know what the default output of the letsencrypt.sh file looks like though, so perhaps the filename would be different.

I notice something else though: the container being used (quay.io/letsencrypt/letsencrypt) is marked as deprecated. I haven't tested the letsencrypt example; I wonder if it still works.
