### ISSUE TITLE
using nbgrader

### ISSUE THREAD

**Issue by Tropus000** [jupyterhub/jupyterhub-deploy-docker#104]
Is it possible to use nbgrader/ngshare with jupyterhub-deploy-docker?

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
