### ISSUE TITLE
docker notebook image is 3 years old

### ISSUE THREAD

**Issue by priamai** [jupyterhub/jupyterhub-deploy-docker#112]
### Proposed change
I have noticed that the single docker image is quite old, this commit is 3 years old.

```
# Single-user Jupyter Notebook server container image
DOCKER_NOTEBOOK_IMAGE=jupyter/minimal-notebook:8ccdfc1da8d5
```

Is there a specific reason to lock it on that version?

### (Optional): Suggest a solution

Maybe use the latest tag?

**Comment by manics** [comment]
This was updated!
