### ISSUE TITLE
How can I enable the sudo option for each user container?

### ISSUE THREAD

**Issue by JesusAlbujas** [jupyterhub/jupyterhub-deploy-docker#130]
Hello everyone, I am grateful for the docker compose template to build a multi-user jupyter service, I would like to be able to allow each container that is created to have the option to use **sudo**. For example, to execute shell code:

~~~
!apt update
~~~

This will return an error, saying that you do not have administrator permissions.

I have investigated exhaustively and I cannot find the possibility of enabling sudo, thank you in advance.

**Comment by jeroenvanderschoot** [comment]
> Hello everyone, I am grateful for the docker compose template to build a multi-user jupyter service, I would like to be able to allow each container that is created to have the option to use **sudo**. For example, to execute shell code:
> 
> ```
> !apt update
> ```
> 
> This will return an error, saying that you do not have administrator permissions.
> 
> I have investigated exhaustively and I cannot find the possibility of enabling sudo, thank you in advance.

Did you figure out how to do this?
