### ISSUE TITLE
`make build` fails when using Let's Encrypt

### ISSUE THREAD

**Issue by thewtex** [jupyterhub/jupyterhub-deploy-docker#20]
The `make build` target depends on `check-files`, which looks for the SSL certificate and key. However, when using Let's Encrypt (`examples/letsencrypt/`), the SSL certificate and key are not stored in the same location because they are brought in via a Docker data volume.

Perhaps `check-files` should first check for the data volume?

**Comment by minrk** [comment]
This is fixed by #20. Thanks for testing!

**Comment by thewtex** [comment]
Hey, thanks!
