### ISSUE TITLE
Userlist must be known a priori

### ISSUE THREAD

**Issue by thewtex** [jupyterhub/jupyterhub-deploy-docker#21]
When using the deployment for a workshop, tutorial, etc, the userlist is not necessarily known beforehand. It is preferred to not require a whitelist of users.

In the past, I also tried `tmpnb`. The problem that occurs in this case is that users will go to the site many times, hit refresh repeatedly, try to reconnect after loosing their connection on poor or Wifi or coming back from a break, etc. Since their session is not re-used, a new container is launched each time, which quickly consumes compute resources.

CC: @willingc @minrk

**Comment by willingc** [comment]
@minrk I spoke with @thewtex at PyData Carolinas about this and asked him to file an issue.

General use case: Best practice for setting up users at the start of a workshop (when users are not known ahead of time)

tmpnb question: Does the current version of tmpnb launch new containers when users refresh or visit the site repeatedly?

cc @rgbkrk

**Comment by parente** [comment]
In normal use, tmpnb has a pre-provisioned pool of running notebook containers. If users visit the root of the tmpnb site repeatedly, they can exhaust the pool. Idle containers are killed off after a while and the pool refreshed.

**Comment by thewtex** [comment]
> If you don't configure a whitelist, I believe anyone who can authenticate using whatever mechanism you've configured is also authorized.

This would be nice, but I did not test it or see it in the docs. However, there would not be an *admin* user in this case?

**Comment by rgbkrk** [comment]
> tmpnb question: Does the current version of tmpnb launch new containers when users refresh or visit the site repeatedly?

That's correct. It's a fresh container everytime you visit the base url (e.g. `https://tmpnb.org`). You keep the same container if you go back to the notebook URL (and if it still exists). I'm still a fan of there being cookies that would put people back to their prior container if available.

**Comment by parente** [comment]
> This would be nice, but I did not test it or see it in the docs.

The empty whitelist doc appears on the traitlet which means it should appear when you run `jupyterhub --help-all`. Here it is in source:

https://github.com/jupyterhub/jupyterhub/blob/f1bdf6247abe3f41d571ea94116cf64ec7ed45df/jupyterhub/auth.py#L42

>  However, there would not be an admin user in this case?

You can still define admin users. You just have to know what their usernames will be when they authenticate for the first time. For example, I can deploy Jupyter Hub with:

1. GitHub OAuth
2. an empty whitelist 
3. `parente` in the admin list

to get an instance where anyone with a GitHub account can log in, but only GitHub user parente has admin capabilities on the Hub.

**Comment by willingc** [comment]
To recap this and add it to the docs:

Best practice for using JupyterHub for a workshop (when users are not known ahead of time):

1. Set up JupyterHub using OAuthenticator for GitHub authentication
2. Configure whitelist to be an empty list in `jupyterhub_config.py`
3. Configure admin list to have workshop leaders (i.e. admins) such as `parente` in the above example.

Users will need a GitHub account to login and be authenticated by the Hub.

**Comment by thewtex** [comment]
+1, Thanks @willingc, @parente, @rgbkrk !

**Comment by willingc** [comment]
Closing and filed issue for docs https://github.com/jupyterhub/jupyterhub/issues/763
