### ISSUE TITLE
adding another route to the spawned user container

### ISSUE THREAD

**Issue by bertrandrigaud** [jupyterhub/jupyterhub-deploy-docker#32]
For my use case, I need to install and launch a tomcat server inside the notebook container. This server will interact with the notebook server via a notebook widget. I need to install this tomcat server inside the container to access the user's workdir data. The connection process from a notebook to the tomcat server (via a widget) adds and execute a javascript on the client side, so that the url given starts from the client (not from the notebook server). So I need to access the current user container to initialize my tomcat application.
So here is my question:
I would like to know if there is a way to add a route at user container spawning time, in the same time jupyterhub creates the https://myserver/user/username route to the user notebook ? 
for example: 
https://myserver/user/username goes through 443--jupyterhub--8888--user-container:notebookserver
and in the same time
https://myserver/user/username/tomcatserver through 443--jupyterhub--8443--user-container:tomcatserver

![docker_architecture](https://cloud.githubusercontent.com/assets/23723747/23216902/d484cf1a-f917-11e6-973f-f57b2243b35a.png)

**Comment by manics** [comment]
Hi :wave: This is an old issue and the repository has been updated. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
