### ISSUE TITLE
What is meant in the README by "not for production use"?

### ISSUE THREAD

**Issue by bryanwweber** [jupyterhub/jupyterhub-deploy-docker#39]
In the README, there is a disclaimer that one should not use this repo to deploy for a production environment:

> **Disclaimer:** This deployment is **NOT** intended for a production environment. 

What is meant by this warning? What could go wrong in a production environment? What are the possible holes here that warrant the disclaimer?

Thanks!

**Comment by jtyberg** [comment]
The disclaimer is intended to make it very clear that this is a reference implementation that has NOT been vetted for a production setting. (It does not meet traditional requirements in terms of uptime, scalability, etc.).

If I were hosting JupyterHub for a one-time classroom setting with 10 students, I might reach for a simple, single-host setup that this repo provides. If I were looking for a more scalable and resilient solution for deploying JupyterHub, I might look [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s).

**Comment by bryanwweber** [comment]
OK thanks for the clarification. What about a semester-long classroom setting with 200 students? Are there any guides for scaling without using commercial cloud services (AWS, etc.)?

**Comment by minrk** [comment]
For something like that, I would highly recommend the newer [zero to jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/latest/) guide for setting up JupyterHub on kubernetes on cloud providers, which @jtyberg linked above. It's from scratch, and includes instructions for a few cloud providers, including AWS. Our experience has been best so far with Google, if you have no prior preferences of your own, but they all should work.

**Comment by parente** [comment]
Minimally, should the README here link to the new zero to jupyterhub repo for production use? Long term, do we consider this repo deprecated by the zero to jupyterhub project?
