### ISSUE TITLE
How to redirect HTTP requests to HTTPS

### ISSUE THREAD

**Issue by bryanwweber** [jupyterhub/jupyterhub-deploy-docker#40]
I have set up an instance of JupyterHub with this repo as the reference. However, requests from the client browser to `http://mysite.mydomain` result in `ERR_ADDRESS_UNREACHABLE` in Chrome, whereas requests to `https://mysite.mydomain` are successful and everything seems to work. Do I have a configuration problem in, e.g., my firewall, or is the proxy not redirecting requests properly? Or something else?

Thanks!

**Comment by jtyberg** [comment]
Current versions of JupyterHub default to listening on secure HTTPS only. Secure by default, if you will. It will listen on [one port or the other](https://github.com/jupyterhub/jupyterhub/blob/48f1da1b8d5bbe01b4a5fc7aa77d4ed73134d394/jupyterhub/singleuser.py#L246).

**Comment by bryanwweber** [comment]
So I need to set up some other service (e.g., nginx) if I want to redirect HTTP requests to HTTPS. OK, thank you!

**Comment by taschini** [comment]
It is actually possible, since at least v. 0.8.2, by adding the following to your `jupyterhub_config.py` file:

```python
c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--redirect-port', '80']
```
