### ISSUE TITLE
R Kernel

### ISSUE THREAD

**Issue by inkrement** [jupyterhub/jupyterhub-deploy-docker#46]
Hi, would you be so kind and add some documentation how to add/enable R kernels for all users? I tried to adopt https://github.com/jupyter/docker-stacks/blob/master/r-notebook/Dockerfile without success. To do so, I copied the fixed-permissions and the R pre-requisites & R packages except USER $NB_USER. Fixed-permissions did not work because of missing permissions and it does not work without it. 

EDIT:
Or would it be possible to activate the conda-interface somehow? Even as admin I am not able to see it on a fresh setup.

**Comment by RobinFrcd** [comment]
Hi,
I think the easiest way to achieve that is just to change the notebook image here: https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/.env#L19 

For example, you have this **very complete** [data science notebook](https://hub.docker.com/r/jupyter/datascience-notebook/) which includes R kernels.

**Comment by inkrement** [comment]
Thanks!
