### ISSUE TITLE
OAuth 404 error

### ISSUE THREAD

**Issue by geoHeil** [jupyterhub/jupyterhub-deploy-docker#53]
I get an 404 when clicking on login
https://github.com/jupyterhub/oauthenticator/issues/141

Following along with https://github.com/jupyterhub/jupyterhub-deploy-docker I created https://github.com/viennadatasciencegroup/jupyterhub which hosts a Jupiter hub at https://hub.vdsg.at/hub/login

However, when clicking on the login button 

```
[I 2017-10-24 05:26:19.722 JupyterHub oauth2:82] OAuth redirect: 'https://hub.vdsg.at/hub/oauth_callback'
jupyterhub | [I 2017-10-24 05:26:19.724 JupyterHub log:122] 302 GET /hub/oauth_login?next= → https://github.com/login/oauth/authorize?state=eyJzdGF0ZV9pZCI6ICJjNDgzZjZlMjk3MDE0NTRhYjE4ZjgyY2MxMjMxZTY0MiIsICJuZXh0X3VybCI6ICIifQ==&response_type=code&client_id=&redirect_uri=https://hub.vdsg.at/hub/oauth_callback (@::ffff:78.46.228.137) 3.06ms
```
the logs only show an redirect and GitHub itself returns an 404

The IP of the spawner is already set via docker-DNS 
- https://github.com/viennadatasciencegroup/jupyterhub/blob/master/jupyterhub_config.py#L46
- https://github.com/viennadatasciencegroup/jupyterhub/blob/master/docker-compose.yml#L30

To me the redirect URL with spaces and empty `client_id` parameter as well as binary `(@::ffff:78.46.228.137)` looks a bit weird.

**Comment by gaurcs** [comment]
Did you ever figure this out?

**Comment by geoHeil** [comment]
yes, was a problem in the oath configuration

Vasu Gaur <notifications@github.com> schrieb am Fr., 12. Jan. 2018 um
01:41 Uhr:
