### ISSUE TITLE
User jovyan with nbgrader 0.5 and JupyterHub 0.8

### ISSUE THREAD

**Issue by bbhopesh** [jupyterhub/jupyterhub-deploy-docker#54]
Apologies for the not so clear title.

I am using this repo's setup to have each user's notebook run inside a separate docker container. Unix username inside docker container is `jovyan` for all the users. This is okay because each of them have separate docker volumes.

Now the problem arises when I also try to use `nbgrader` in this setup. `nbgrader` uses unix username as student id instead of hub userid. This is causing one student's submission to override other's. Essentially there is just one student, `jovyan`, in the system. 

Instead of having each student's unix name be `jovyan`, I can create new users from github id on the fly and then everything will work fine but I am wondering if there is a better way. 

Is there a simpler way to tell nbgrader to use the id used by hub to authenticate user instead of unix username? In `nbgrader 0.4`, there seems to be something called `HubAuth` but that is gone is `nbgrader 0.5`

If yes, a followup question is can nbgrader see whether user is hub admin or not and enable/disable Formgrade extension accordingly?

I tried to look through existing issues and also did some web seach to see if there is something already answering my questions but didn't find any. If I have overlooked it, please share the links

**Comment by bbhopesh** [comment]
@minrk @jhamrick

**Comment by bbhopesh** [comment]
I was going throught nbgrader code and it looks like that it always uses unix username on a unix system.

The method in this [utility module ](https://github.com/jupyter/nbgrader/blob/master/nbgrader/utils.py#L164 ) is used by `ExchangeSubmit` class [here](https://github.com/jupyter/nbgrader/blob/master/nbgrader/exchange/submit.py#L46) to create the assignment submission directory name from username.

Username is then extracted from the directory name [here](https://github.com/jupyter/nbgrader/blob/master/nbgrader/exchange/collect.py#L34) in `ExchangeCollect` class.

**Comment by jhamrick** [comment]
You are correct, there is no way in nbgrader currently to have it use the hub username. This is likely to change in a future release once HubShare is implemented (see https://github.com/jupyter/nbgrader/issues/659 ) but that is not likely to be for some time.

> A followup question is can nbgrader see whether user is hub admin or not and enable/disable Formgrade extension accordingly?

No, and I do not think this is something that nbgrader will be able to do in the future either since access to the formgrader is determined by JupyterHub groups, not nbgrader itself (see https://github.com/jupyter/nbgrader/pull/897/files ).

**Comment by bbhopesh** [comment]
Thanks a lot for the quick response. Really appreciate it :)

**Comment by kidig** [comment]
Maybe still interesting :)

It actually possible to change `jovyan` to another username in the separate docker containers.

e.g. for the `jupyterhub/base-notebook` (or similar) you may define a few environment variables: `NB_USER` and `CHOWN_HOME` (for correct permissions in the user's home dir).

For dockerspawner, it also needs to set `notebook_dir` like `/home/{username}/work`.

P.S. -  I did that for my docker swarm jupyterhub cluster! ;)
