### ISSUE TITLE
500 Error when starting Notebook

### ISSUE THREAD

**Issue by rwmajor2** [jupyterhub/jupyterhub-deploy-docker#55]
I have followed the instructions to get setup with JupyterHub and the GitHub Authenticator.  However, I am using my own Docker image, built from jupyter/base-notebook.  Once I log in and authenticate, I get the following message:
```
500 : Internal Server Error
Redirect loop detected. Notebook has jupyterhub version unknown (likely < 0.8), but the Hub expects 0.8.0. Try installing jupyterhub==0.8.0 in the user environment if you continue to have problems.
You can try restarting your server from the home page.
```

What does this mean exactly?  Is this error coming from my individual notebook server?

**Comment by dalg24** [comment]
Looking at @minrk comments on jupyterhub/jupyterhub#709 I suspect your singleuser notebook image does not have a matching version of Jupyterhub.

If you set `DOCKER_NOTEBOOK_IMAGE` in the `.env` file and then do `make notebook_image` it should take care of it for you.  Did you directly edit `jupyterhub_config.py`?

**Comment by rwmajor2** [comment]
@dalg24 Thanks.  I was using my own image and it was slightly older and had jupyterhub 0.7 installed.  I updated and it worked.  Thanks!
