### ISSUE TITLE
Best strategy for sharing notebook data between users

### ISSUE THREAD

**Issue by colbygk** [jupyterhub/jupyterhub-deploy-docker#56]
I have setup a single host instance of jupyterhub for a specific group need. We would like to have a common view between all of the data directories for the users instead of having a separate data directory for each user.  It is not immediately obvious to me which would be the best route to take to enable this when working with the user volumes and mapping a particular host directory to all of the individual jupyter docker instances.

**Comment by dalg24** [comment]
I am not sure whether it is a good idea to "share" notebooks between users but I believe you should be able to do something along these lines:
```diff
diff --git a/jupyterhub_config.py b/jupyterhub_config.py
index dc925dd..7f38a77 100644
--- a/jupyterhub_config.py
+++ b/jupyterhub_config.py
@@ -35,7 +35,10 @@ notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
 c.DockerSpawner.notebook_dir = notebook_dir
 # Mount the real user's Docker volume on the host to the notebook user's
 # notebook directory in the container
-c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
+c.DockerSpawner.volumes = {
+    'jupyterhub-user-{username}': notebook_dir,
+    '/that/particular/host/directory/you/want': '/home/jovyan/shared'
+}
 c.DockerSpawner.extra_create_kwargs.update({ 'volume_driver': 'local' })
 # Remove containers once they are stopped
 c.DockerSpawner.remove_containers = True
```

**Comment by colbygk** [comment]
That's exactly what I needed, thank you.

**Comment by obilodeau** [comment]
That should be documented at the end of the README. I'm sure it's a common use case.

**Comment by fparaggio** [comment]
Can you give more detailed instruction to achieve the shared folder?? I am using these lines:
```
 c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir ,
         'jupyterhub-team-volume': '/home/jovyan/shared'
 }
```
it creates the folder but the user is not allowed to write in it.

**Comment by dalg24** [comment]
@fparaggio Try this:
```bash
$ docker run --rm -v jupyterhub-team-volume:/scratch ubuntu:16.04 chmod -R 777 /scratch
```

**Comment by fparaggio** [comment]
Thanks! That is very helpful!

**Comment by leolurunhe** [comment]
@dalg24 But this command didn't work for me, because I create those docker containers using my Dockerfile, how to grant write permission for that volume in Dockerfile, thanks

**Comment by dalg24** [comment]
@leolurunhe I am sorry, I can't help you much from what you posted.

**Comment by reisman234** [comment]
I also have that problem, that i dont get access when i mount a location with the following snippet 

```
c.DockerSpawner.volumes = {
    'jupyterhub-user-{username}': notebook_dir},
    '/home/user/workspace/data':'/home/jovyan/data' }
```

ls of the working directory in the notebook, with the shared data folder.

> drwsrwsr-x 1 jovyan users 4.0K Oct 26 00:17 .cache
> drwsrwsr-x 1 jovyan users 4.0K Oct 24 13:09 .conda
> drwsrws--- 1 jovyan users 4.0K Oct 26 00:17 .config
> drwxrwx--- 2   1007  1003 5.9M Nov  8 12:43 data
> drwxr-sr-x 5 jovyan users 4.0K Nov 12 16:14 .ipython
> drwsrws--- 2 jovyan users 4.0K Oct 25 23:20 .jupyter
> drwx--S--- 3 jovyan users 4.0K Nov 12 16:14 .local
> -rw-rw-r-- 1 jovyan users  807 Apr  4  2018 .profile
> drwsrwsr-x 3 jovyan users 4.0K Nov 12 15:32 work


Are there some approches to get this to work ? Maybe by creating a docker volume with that host location ? how to create such volume.

**Comment by TiemenSch** [comment]
@reisman234 where did you do the chmod? Even when I bind using the "rw" mode in the DockerSpawner, I can't create any files in the directory.

**Comment by reisman234** [comment]
>
> @reisman234 where did you do the chmod? Even when I bind using the "rw" mode in the DockerSpawner, I can't create any files in the directory.
>  
> Edit:
> OK, so I've changed the permissions on the volume directory on the Docker host and then it works, but I'd like to fix the permissions at volume creation instead of manually afterwards. Any ideas?

Hi, as you said, i changed that directory that should be mounted via

**Comment by MasonM** [comment]
@TiemenSch The reason the `jupyterhub-user-xxx` volume works out of the box is because it's mapped to `/home/jovyan/work`, which already exists in the image with the right permissions. See the `Dockerfile`: https://github.com/jupyter/docker-stacks/blob/6fb3eca57bd30fd4d18701de54e0ea6ceb057e65/base-notebook/Dockerfile#L58

I fixed this by adding the following line to `singleuser/Dockerfile`:
```
RUN mkdir /home/jovyan/shared && chown jovyan.users /home/jovyan/shared
```

**Comment by nuraym** [comment]
@dalg24 I am trying to achieve a shared directory for all users. I created a shared-file folder in my Jupyterhub.
Added this to my jupyterhub_config.py

notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/jupyter' c.DockerSpawner.notebook_dir = notebook_dir c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir, 'shared-data/volumes': '/home/jovyan/shared' }
I am launching JupyterHub from my terminal locally using jupyterhub -f jupyterhub_config.py
What am I missing?
