### ISSUE TITLE
DOCKER_NOTEBOOK_IMAGE vs. LOCAL_NOTEBOOK_IMAGE

### ISSUE THREAD

**Issue by theotheo** [jupyterhub/jupyterhub-deploy-docker#57]
Hi there! 

I can't figure out a difference between `DOCKER_NOTEBOOK_IMAGE` and `LOCAL_NOTEBOOK_IMAGE`. Which one should I change to specify user's Notebook server image? I was sure that `DOCKER_NOTEBOOK_IMAGE` is used to achieve this. But at the end, only after I changed `LOCAL_NOTEBOOK_IMAGE` all began to work.

**Comment by dalg24** [comment]
I think the intent was actually for you to specify `DOCKER_NOTEBOOK_IMAGE` in the .env file ([here](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/691815382be4471e9171e62e0762f9a5bbeecfb7/.env#L27])) and then do `make notebook_image` before you launch the hub.

This will attempt to pull your image from DockerHub and install the matching version of JupyterHub on top of it.  If you want more details you can look [here](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/691815382be4471e9171e62e0762f9a5bbeecfb7/Makefile#L50-L57) and [here](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/691815382be4471e9171e62e0762f9a5bbeecfb7/singleuser/Dockerfile).  It is a bit confusing but it does make things easier.
