### ISSUE TITLE
Files and more

### ISSUE THREAD

**Issue by Rachidramadan1990** [jupyterhub/jupyterhub-deploy-docker#67]
Hello
I have setup jupyter-deploy-docker and it works so far.
Now I want to work with data-sets. Every user who has access to the notebook should also be able to read the data. Since the data can have a size of 5-100 GB, I dont want to copy the data in the container. Files with exercises for that data should be copied an be readable and writeable in the container for the users. 
Is there a build in solution for that using a docker deployment?

**Comment by dalg24** [comment]
Have you looked at #56 ?

**Comment by helloworld199011** [comment]
Thank you very much!
