### ISSUE TITLE
Fails if behind proxy

### ISSUE THREAD

**Issue by moppymopperson** [jupyterhub/jupyterhub-deploy-docker#69]
This currently doesn't work if you're on a proxied network.
I've made some changes that have fixed most of it, but I haven't completely gotten it working yet.

This is from the `make notebook_image` command.

```
e1677043235c: Pulling from jupyter/minimal-notebook
Status: Image is up to date for jupyter/minimal-notebook:e1677043235c
docker build -t jupyterhub-user \
	--build-arg JUPYTERHUB_VERSION=0.8.0 \
	--build-arg DOCKER_NOTEBOOK_IMAGE=jupyter/minimal-notebook:e1677043235c \
	singleuser
Sending build context to Docker daemon  2.048kB
Step 1/4 : ARG DOCKER_NOTEBOOK_IMAGE
Step 2/4 : FROM $DOCKER_NOTEBOOK_IMAGE
 ---> c86d7e5f432a
Step 3/4 : ARG JUPYTERHUB_VERSION
 ---> Using cache
 ---> be71e0724cd5
Step 4/4 : RUN python3 -m pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION
 ---> Running in 02c9c26fcc9b
Collecting jupyterhub==0.8.0
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f0f764710>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/jupyterhub/

```

**Comment by dalg24** [comment]
The problem comes from docker's DNS not being properly configured on your machine.

**Comment by dalg24** [comment]
You may look at [this post](https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/) to see one way fix this issue.

**Comment by moppymopperson** [comment]
In my particular case I have to pass credentials to the proxy server, so the solution was to pass `http_proxy` and `https_proxy` environment variables to the docker build contexts.

I basically added a couple lines to the docker compose file and Makefile and that got everything working. I doubt there's much interest in merging this changes back into the upstream, but if you want them let me know and I'll submit a PR.
