### ISSUE TITLE
Nvidia-docker-compose

### ISSUE THREAD

**Issue by Rachidramadan1990** [jupyterhub/jupyterhub-deploy-docker#70]
Hello,

we want to use this deployment with a couple of powerful GPU.  As far as I understand, using docker-compose will not make full use of our GPUs. To use nvidia-docker-compose, is it enough to just use the new command or do we have to make additional changes in the config file?
Furthermore, is there a way to limit the amount of GPU used by each single user notebook?

Best!

**Comment by dalg24** [comment]
If you are running nvidia-docker 2.0, you should be able to do something like:
```Python
c.DockerSpawner.extra_create_kwargs.update({ 'runtime': 'nvidia' })
```

**Comment by mathematicalmichael** [comment]
see https://github.com/iot-salzburg/gpu-jupyter/
