### ISSUE TITLE
no such image: jupyterhub-user

### ISSUE THREAD

**Issue by alexraju91** [jupyterhub/jupyterhub-deploy-docker#72]
In .env file, variable `LOCAL_NOTEBOOK_IMAGE` is set to `jupyterhub-user`. And this is used in docker-compose.yml
```
DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
```

So, If I'm right, we need to set the jupyter-notebook/jupyter-lab image to this variable instead of `DOCKER_NOTEBOOK_IMAGE` as mentioned in documenation.

**Comment by lrpauley** [comment]
also ran into the no such image problem, but fixed using the ```make notebook_image``` command described in the readme

**Comment by manics** [comment]
The repo should be working, and is tested in CI
