### ISSUE TITLE
Using Kubernetes?

### ISSUE THREAD

**Issue by syoh** [jupyterhub/jupyterhub-deploy-docker#79]
Can Kubernetes spawner be used with this installation?

**Comment by minrk** [comment]
It might with some work, but it doesn't make a great deal of sense. Typically kubespawner is used with the jupyterhub helm chart: https://zero-to-jupyterhub.readthedocs.io

**Comment by syoh** [comment]
In our department, we have many single-notebook images that are modified at instructors' requests. We found that these images need to be tested in Jupyterhub environment to make sure everything works as expected. (nbsessionproxy with auto-redirect, container settings, etc.)
Our production environment uses Kubernetes spawner, so the current reference installation doesn't allow us to replicate the spawner and the configurations
Any suggestions?
