### ISSUE TITLE
500 internal server error when doing gitlab-ce authentication(authentication cookies expires before creating)

### ISSUE THREAD

**Issue by divatemangesh** [jupyterhub/jupyterhub-deploy-docker#83]
I am also getting 500 Internal server error  when autheticating with GITLAB-CE seems like authentication-state  cookies expiration issue

cleared browser cookies and cache and any saved data and in New Tab opened https://localhost
security warning came  like site is not safe  I clicked on proceed safely 
In chrome  ctrl+shift+C>> application >> cookies I can see following entries 
Sign in with gitlab page

Name:- xsrf
Value:- 2|d6b491b6|bf36d80df77faf9466583355e204eb77|1550066103
Expires:-  2020-03-15T13:55:03.000Z

Name:- username-localhost-8888
Value:-"2|1:0|10:1551431956|23:username-localhost-8888|44:MmU4ZDlmY2JkMzRkNDNjNWJhOTJiNmQ4NzNmYjA4NDA=|d5174b5df574432e334f4733f11943c12caf3cf3e05c4b47c7c962937c2a8960"
Expires:- 2020-03-31T09:19:16.000Z
-------------------------------- Once Clicked on Sign in with gitlab  button ----------------------------

> additional one entry came and disappered in less than half second and I landed to GitLab-CE login page but I screen recorded it  to see the disappred entry 

The one which disappeared was 

Name :- oauthenticator-state 
Value:- "2|1:0|10:1552127982|20:oauthenticator-state|120:Z... was not able to see comple value as it was partialy visiable in recording
_**expires :- 2019-03-10T1 ...**_

-------------------Once landed on gitlab-CE login-----------------------------------

Name:- _gitlab_session
Value:- ba46390addc98a11c22e4cd4dd064fdb
Expires:- 2019-03-09T12:39:42.873Z

---------------------loged in to gitlab with username-----------------------------
_gitlab_session
6dc3812c2eb2a0593ed8cb6c4f4f12b6
1969-12-31T23:59:59.000Z

--------------------Once Clicked on authosise in gitlab------------
Name:- _xsrf
Value :- 2|d6b491b6|bf36d80df77faf9466583355e204eb77|1550066103
Expireds:- 2020-03-15T13:55:03.000Z

Name:- username-localhost-8888
Value:- "2|1:0|10:1551431956|23:username-localhost-8888|44:MmU4ZDlmY2JkMzRkNDNjNWJhOTJiNmQ4NzNmYjA4NDA=|d5174b5df574432e334f4733f11943c12caf3cf3e05c4b47c7c962937c2a8960"
Expires:- 2020-03-31T09:19:16.000Z

GOT 500 INTERNAL SERVER ERROR

If issue is due authentication state  cookies expiring before creating  then how to  solve it

**Comment by manics** [comment]
Hi :wave: This is an old issue and the repository has been updated. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
