### ISSUE TITLE
'make build' fails with Conda

### ISSUE THREAD

**Issue by karthi4k** [jupyterhub/jupyterhub-deploy-docker#91]
Followed all the configurations and then it fails in build stage with error - ModuleNotFoundError: No module named 'conda'.

Below is the full error trace,

make build
docker-compose build
hub-db uses an image, skipping
Building hub
Step 1/9 : ARG JUPYTERHUB_VERSION
Step 2/9 : FROM jupyterhub/jupyterhub-onbuild:$JUPYTERHUB_VERSION
# Executing 1 build trigger
 ---> Using cache
 ---> b6927b9a433f
Step 3/9 : RUN /opt/conda/bin/conda install -yq psycopg2=2.7 &&     /opt/conda/bin/conda clean -tipsy &&     /opt/conda/bin/pip install --no-cache-dir         oauthenticator==0.8.*         dockerspawner==0.9.*
 ---> Running in 794099d91a50
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - psycopg2=2.7

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
ERROR: Service 'hub' failed to build: The command '/bin/sh -c /opt/conda/bin/conda install -yq psycopg2=2.7 &&     /opt/conda/bin/conda clean -tipsy &&     /opt/conda/bin/pip install --no-cache-dir         oauthenticator==0.8.*         dockerspawner==0.9.*' returned a non-zero code: 1

**Comment by karthi4k** [comment]
Thanks @obilodeau. It works :-)

**Comment by dan91** [comment]
I ran into this problem on Ubuntu 18.04 following the Readme instructions.

**Comment by Alcamech** [comment]
Still experiencing this issue

**Comment by mathematicalmichael** [comment]
experiencing this now

**Comment by mathematicalmichael** [comment]
> The current Docker image on which your build is based seems to ship a broken version of `conda`. I was bitten by the same problem and couldn't pin the specific problem.
> 
> I modified the `RUN` statement to update conda first. Here's the patch:
> 
> ```diff
> diff --git a/Dockerfile.jupyterhub b/Dockerfile.jupyterhub
> index 7f8ccd7..597e309 100644
> --- a/Dockerfile.jupyterhub
> +++ b/Dockerfile.jupyterhub
> @@ -4,7 +4,8 @@ ARG JUPYTERHUB_VERSION
>  FROM jupyterhub/jupyterhub-onbuild:$JUPYTERHUB_VERSION
>  
>  # Install dockerspawner, oauth, postgres
> -RUN /opt/conda/bin/conda install -yq psycopg2=2.7 && \
> +RUN /opt/conda/bin/conda update -n root conda && \
> +    /opt/conda/bin/conda install -yq psycopg2=2.7 && \
>      /opt/conda/bin/conda clean -tipsy && \
>      /opt/conda/bin/pip install --no-cache-dir \
>          oauthenticator==0.8.* \
> ```
> 
> make build now works

`/bin/sh /opt/conda/bin/conda: command not found`

**Comment by muh-hassani** [comment]
I faced the same issue, and updating conda does not solve the issue.

**Comment by underw8** [comment]
> > The current Docker image on which your build is based seems to ship a broken version of `conda`. I was bitten by the same problem and couldn't pin the specific problem.
> > I modified the `RUN` statement to update conda first. Here's the patch:
> > ```diff
> > diff --git a/Dockerfile.jupyterhub b/Dockerfile.jupyterhub
> > index 7f8ccd7..597e309 100644
> > --- a/Dockerfile.jupyterhub
> > +++ b/Dockerfile.jupyterhub
> > @@ -4,7 +4,8 @@ ARG JUPYTERHUB_VERSION
> >  FROM jupyterhub/jupyterhub-onbuild:$JUPYTERHUB_VERSION
> >  
> >  # Install dockerspawner, oauth, postgres
> > -RUN /opt/conda/bin/conda install -yq psycopg2=2.7 && \
> > +RUN /opt/conda/bin/conda update -n root conda && \
> > +    /opt/conda/bin/conda install -yq psycopg2=2.7 && \
> >      /opt/conda/bin/conda clean -tipsy && \
> >      /opt/conda/bin/pip install --no-cache-dir \
> >          oauthenticator==0.8.* \
> > ```
> > 
> > 
> > make build now works
> 
> `/bin/sh 1: /opt/conda/bin/conda: command not found`

Try to remove ` /opt/conda/bin/conda clean -tipsy && \` line. And rebuild.

**Comment by Soap2G** [comment]
Hey everyone, I looked into this issue, and I found out that for some reason `/opt/conda/bin/conda` does not exist. In particular, the `/opt` folder is empty. So I hard-installed conda (following [this link](https://github.com/jupyterhub/jupyterhub-the-hard-way/blob/master/docs/installation-guide-hard.md)), and I added the following lines to the dockerfile:
```
RUN curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg && \
        install -o root -g root -m 644 conda.gpg /etc/apt/trusted.gpg.d/ && \
        echo "deb [arch=amd64] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" | tee /etc/apt/sources.list.d/conda.list && \
        apt update && \
        apt install conda && \ 
```
before the usual `/opt/conda/bin/conda update -n root conda && \` etc.

**It worked**. Hope it can help you :D
