### ISSUE TITLE
Using AWS Storage with jupyterhub-deploy-docker

### ISSUE THREAD

**Issue by Deepanshu2017** [jupyterhub/jupyterhub-deploy-docker#93]
Hello,

This should be marked as `Help Wanted` or `Question`.

I am using the jupyterhub-deploy-docker with Github Authentication. I have the entire setup up and running. Now I want to use th AWS as a backend, where all users notebook would be saved inside the `bucket/GibhubUserName/{Userdata}`.

I am using `s3contents` for this. I am able to setup and run the s3contents with Jupyter separately but I am not able to manage to merge both them. In short I am not able to use the `s3contents` inside ` jupyterhub-deploy-docker`.

I have added these lines at the top of my `jupyterhub_config.py` file.

```
c = get_config()

c.NotebookApp.contents_manager_class = S3ContentsManager
c.S3ContentsManager.access_key_id = "KEYID"
c.S3ContentsManager.secret_access_key = "ACCESSKEY"
c.S3ContentsManager.endpoint_url = "ENDPOINT"
c.S3ContentsManager.bucket = "BUCKET"
```

As I am on a very tight deadline, Any help would be much appreciated @minrk @dalg24   (Sorry for direct mention)

**Comment by mathematicalmichael** [comment]
hope you figured this out, but if not, isn't it technically possible to mount your s3 bucket to whatever machine the jupyterhub app is working on? Trick the computer into thinking it's a local volume somehow seems like the "easy" way here, but perhaps not correct.

**Comment by manics** [comment]
Hi :wave: This is an old issue and the repository has been updated. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
