### ISSUE TITLE
Spawner failed to start with the custom example

### ISSUE THREAD

**Issue by kenenbek** [jupyterhub/jupyterhub-deploy-docker#95]
I built an image in this [directory](https://github.com/jupyterhub/jupyterhub-deploy-docker/tree/master/examples/custom-notebook-server):
`docker build -t custom-notebook-server .
`
Then I tried to run it:
`docker run --rm -it custom-notebook-server`

But it gives me an error:
```
[W 2019-12-23 17:43:30.945 SingleUserNotebookApp configurable:159] Config option `open_browser` not recognized by `SingleUserNotebookApp`, do you mean : `browser`
[W 2019-12-23 17:43:30.948 SingleUserNotebookApp configurable:159] Config option `open_browser` not recognized by `SingleUserNotebookApp`, do you mean : `browser`
[W 2019-12-23 17:43:30.950 SingleUserNotebookApp configurable:159] Config option `open_browser` not recognized by `SingleUserNotebookApp`, do you mean : `browser`
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 297, in <module>
    main()
  File "/opt/conda/bin/jupyterhub-singleuser", line 293, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1023, in initialize
    self.init_webapp()
  File "/opt/conda/bin/jupyterhub-singleuser", line 261, in init_webapp
    s['hub_api_key'] = env.pop('JPY_API_TOKEN')
  File "/opt/conda/lib/python3.5/_collections_abc.py", line 727, in pop
    value = self[key]
  File "/opt/conda/lib/python3.5/os.py", line 683, in __getitem__
    raise KeyError(key) from None
KeyError: 'JPY_API_TOKEN'
```

Is it normal behaviour? Because I can't configure jupyterhub to start a custom container for users and probably problem in this [Dockerfile](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/examples/custom-notebook-server/Dockerfile).

**Comment by kenenbek** [comment]
I have this errpr when I try to lauch a custom notebook server from [examples folder](https://github.com/jupyterhub/jupyterhub-deploy-docker/tree/master/examples/custom-notebook-server).
`[W 2019-12-23 19:14:00.701 JupyterHub web:1667] 500 GET /hub/user/kenenbek/ (::ffff:92.242.58.11): Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2019-12-23T19:13:51.834730009Z]. The logs for kenenbek may contain details.`

**Comment by kenenbek** [comment]
The default image is working but the error happens when I change the environmental variable `DOCKER_NOTEBOOK_IMAGE` and `.env` file.

**Comment by mathematicalmichael** [comment]
your custom image needs to play nice with what's expected. 
meaning, you need to have the exact right jupyterhub version installed, notebook, lab (optional?), etc.
the dockerfiles in the `jupyter/docker-stacks` repo are of help. When I base builds `FROM` one of those, things generally work pretty well (notwithstanding hub version mismatches)

**Comment by manics** [comment]
Hi :wave: This is an old issue and the repository has been updated. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
