### ISSUE TITLE
Q: A few questions about the JupyterHub via Docker deployment model ...

### ISSUE THREAD

**Issue by nmvega** [jupyterhub/jupyterhub-deploy-docker#99]
Hello Friends:

I'm considering using this **deployment model** -- `https://github.com/jupyterhub/jupyterhub-deploy-docker` -- for deploying `JupyterHub via Docker` on a PC with very robust specs (i.e. a high-end gaming PC, though I don't use it for that). Before selecting this **deployment model** road, I'd like to ask friends here a few questions.

1. My use-case will be _giving screenshare classes to between 10 to 20 students_. Recognizing that it depends on what Notebook cells would be concurrently doing, generally speaking, is this user size reasonable for this **deployment model** (again `JupyterHub via Docker` on a stout PC).

2. On that same PC, I have `GitLab CE` installed, which I would like to use as the `OAuth` provider (instead of `GitHub`). Is there anything with this **deployment model** that would prevent configuring that? I suspect I would create a API App on my `GitLab CE` instance instead of `GitHub` and use that instead.

3. Finally, is there anything in this **deployment model** that would prevent containers from accessing services / ports running on the `bare-metal` PC host itself, for example, say, `mongodb` or whatever else? From what I read, containers use the same `Docker network`, but can they access the bare-metal network, too? I can figure out how to do that -- I'm really just trying to understand if there are network show-stoppers before pressing on with this **deployment model**.

Thank you very much in advance!

**Comment by mathematicalmichael** [comment]
nothing's stopping 2. lots of oauth methods supported.
you can look into jupyter-server-proxy for proxying applications within the same container. within the same network isn't a problem, so you can containerize mongo... but as far as access to services on the bare metal... well, if your browser can hit it, the app should be able to as well. you probably won't be able to pass the single port into all of the containers at once

10-20 students on a stout PC ...
not sure what this means. If you have 8 cores + 32GB of RAM, I think it'll be _okay_ as long as you don't push it too hard.
I've done concurrent work on a 2Gb 1 core machine with one other person, and it was a noticeable difference but absolutely bearable

**Comment by nmvega** [comment]
> nothing's stopping 2. lots of oauth methods supported.
> you can look into jupyter-server-proxy for proxying applications within the same container. within the same network isn't a problem, so you can containerize mongo... but as far as access to services on the bare metal... well, if your browser can hit it, the app should be able to as well. you probably won't be able to pass the single port into all of the containers at once
> 
> 10-20 students on a stout PC ...
> not sure what this means. If you have 8 cores + 32GB of RAM, I think it'll be _okay_ as long as you don't push it too hard.
> I've done concurrent work on a 2Gb 1 core machine with one other person, and it was a noticeable difference but absolutely bearable

Hi @mathematicalmichael 

Thank you for your reply and sharing your experiences. I do apologize for my delay in expressing gratitude (I'm usually quite prompt ... almost always on the order hours, not months. LoL). =:) Thank you.

**Comment by manics** [comment]
Hi! Support questions like this are best handled on https://discourse.jupyter.org/
